services:
  - type: web
    name: cueboard
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false