services:
  - type: web
    name: cueboard
    env: docker
    plan: free
    healthCheckPath: /
    disks:
      - name: database
        mountPath: /var/data/db
        sizeGB: 1
    envVars:
      - key: DATABASE_PATH
        value: /var/data/db/cueboard.db
      - key: JWT_SECRET
        generateValue: true 
      - key: NODE_ENV
        value: production